### PR TITLE
fix: update web3 isConnected() (#19)

### PR DESCRIPTION
**Pull request by helloibis**
This is needed as a companion to https://github.com/ApeWorX/ape/pull/1082 since the plugin uses ape's web3 dependency

### CODE REVIEW

**Comment by helloibis** [comment]
@unparalleled-js just a heads up, this plugin is affected by the rinkeby removal which is causing tests to fail

**Comment by helloibis** [comment]
@unparalleled-js @NotPeopling2day looks like the test failures here are actually a web3 thing? Saying that it's likely connected to a PoA chain, is there more that needs to be removed with regards to the unsupported networks?

**Comment by helloibis** [comment]
> @unparalleled-js @NotPeopling2day looks like the test failures here are actually a web3 thing? Saying that it's likely connected to a PoA chain, is there more that needs to be removed with regards to the unsupported networks?

Bump cc @unparalleled-js @NotPeopling2day

**Comment by unparalleled-js** [comment]
> > @unparalleled-js @NotPeopling2day looks like the test failures here are actually a web3 thing? Saying that it's likely connected to a PoA chain, is there more that needs to be removed with regards to the unsupported networks?

I am thinking something like this commit to fix the strange PoA issue: https://github.com/ApeWorX/ape-hardhat/pull/98/commits/cc3337c70c0a24d5b13494bdd2539aca1a19b2ec

But I am not 100% sure what is going on and also experiencing other oddities / failures on that linked branch

**Comment by helloibis** [comment]
Merged in https://github.com/ApeWorX/ape-foundry/pull/22 but still having PoA issues just related around the Goerli impersonation test. Just so we can get the web3 related updates out we're going to merge this now and keep an eye on the PoA thing that's happening

**Pull request merged**
