### PR TITLE
fix: update web3 isConnected()

### PR DESCRIPTION
**Pull request by helloibis**
This is needed as a companion to https://github.com/ApeWorX/ape/pull/1082 since the plugin uses ape's web3 dependency

### CODE REVIEW

**Review by unparalleled-js — APPROVED** [review]

**Comment by unparalleled-js** [comment]
Can we fix the `mypy` issue?

**Comment by unparalleled-js** [comment]
Oh I see, it require ape release. Perhaps let's keep these as drafts until Ape releases

**Comment by helloibis** [comment]
> Oh I see, it require ape release. Perhaps let's keep these as drafts until Ape releases

Okay, I was about to ask since the test failures are from the same issue

**Comment by helloibis** [comment]
Merging this to an upstream branch so that tests and secrets can work 👀

**Pull request merged**
